[package]
name = "k256"
description = "K-256 (secp256k1) elliptic curve"
version = "0.3.0"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/elliptic-curve"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/k256"
readme = "README.md"
edition = "2018"
categories = ["cryptography", "cryptography::cryptocurrencies", "no-std"]
keywords = ["bitcoin", "crypto", "ecc", "ethereum", "secp256k1"]

[dependencies.elliptic-curve]
version = "0.4"
path = "../elliptic-curve-crate"
default-features = false
features = ["weierstrass"]

[dependencies.zeroize]
version = "1"
optional = true
default-features = false

[dev-dependencies]
fiat-crypto = "0.1.0"
hex = "0.4"
proptest = "0.9"
rand_core = { version = "0.5", features = ["getrandom" ]}

[features]
default = ["arithmetic", "std"]
arithmetic = []
rand = ["elliptic-curve/rand_core"]
test-vectors = []
std = ["elliptic-curve/std"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
