[package]
name = "k256"
description = "secp256k1 elliptic curve"
version = "0.1.1" # Also update html_root_url in lib.rs when bumping this
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/elliptic-curve"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/k256"
readme = "README.md"
edition = "2018"
categories = ["cryptography", "cryptography::cryptocurrencies", "no-std"]
keywords = ["bitcoin", "crypto", "ecc", "ethereum"]

[dependencies.elliptic-curve]
version = "0.3"
path = "../elliptic-curve-crate"
default-features = false
features = ["weierstrass"]

[dependencies.subtle]
version = "2.2.2"
optional = true
default-features = false

[dev-dependencies]
hex = "0.4"
proptest = "0.9"
fiat-crypto = "0.1.0"

[features]
default = ["arithmetic", "std"]
arithmetic = ["subtle"]
test-vectors = []
std = ["elliptic-curve/std"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
