[workspace]
members = [
    "k256",
    "p256",
    "p384",
    "p521"
]

[patch.crates-io]
ecdsa = { git = "https://github.com/RustCrypto/signatures" }
elliptic-curve = { git = "https://github.com/RustCrypto/traits" }
