[workspace]
resolver = "2"
members = [
    "bp256",
    "bp384",
    "k256",
    "p256",
    "p384",
]

[patch.crates-io]
elliptic-curve = { git = "https://github.com/RustCrypto/traits" }
ecdsa = { git = "https://github.com/khonsulabs/signatures", branch = "elliptic-curve-digest" }
