[workspace]
resolver = "2"
members = [
    "bp256",
    "bp384",
    "k256",
    "p224",
    "p256",
    "p384",
    "p521",
    "primeorder"
]

[profile.dev]
opt-level = 2

[patch.crates-io]
ecdsa = { git = "https://github.com/daxpedda/signatures.git", branch = "elliptic-curve-0.13.0-pre.4" }
elliptic-curve = { git = "https://github.com/RustCrypto/traits.git" }
