[workspace]
resolver = "2"
members = [
    "bign256",
    "bp256",
    "bp384",
    "k256",
    "p192",
    "p224",
    "p256",
    "p384",
    "p521",
    "primeorder",
    "sm2"
]

[profile.dev]
opt-level = 2

[patch.crates-io]
elliptic-curve = {git = "https://github.com/RustCrypto/traits.git", branch = "elliptic-curve/linear-combination-ext-trait"}
