[workspace]
members = [
    "bp256",
    "bp384",
    "k256",
    "p256",
    "p384",
]

[patch.crates-io]
base64ct = { git = "https://github.com/RustCrypto/utils.git" }
ecdsa = { git = "https://github.com/RustCrypto/signatures.git" }
elliptic-curve = { git = "https://github.com/RustCrypto/traits.git" }
pkcs8 = { git = "https://github.com/RustCrypto/utils.git" }
