[workspace]
resolver = "2"
members = [
    "bp256",
    "bp384",
    "k256",
    "p256",
    "p384",
]

[patch.crates-io]
der = { git = "https://github.com/rustcrypto/formats" }
ecdsa = { git = "https://github.com/RustCrypto/signatures.git" }
elliptic-curve = { git = "https://github.com/RustCrypto/traits.git" }
sec1 = { git = "https://github.com/rustcrypto/formats" }
