[workspace]
members = [
    "k256",
    "p256",
    "p384",
]

[patch.crates-io]
const-oid = { git = "https://github.com/RustCrypto/utils.git" }
ecdsa = { git = "https://github.com/RustCrypto/signatures" }
elliptic-curve = { git = "https://github.com/RustCrypto/traits" }
pkcs8 = { git = "https://github.com/RustCrypto/utils.git" }
