[package]
name = "p384"
description = "NIST P-384 (secp384r1) elliptic curve"
version = "0.2.0"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/elliptic-curve"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/p384"
readme = "README.md"
edition = "2018"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "nist", "secp384r1"]

[dependencies.elliptic-curve]
version = "= 0.5.0-pre"
default-features = false
features = ["weierstrass"]

[features]
std = ["elliptic-curve/std"]

[package.metadata.docs.rs]
all-features = true
