[package]
name = "sm2"
version = "0.0.0"
description = """
Pure Rust implementation of the SM2 elliptic curve as defined in the Chinese
national standard GM/T 0003-2012 as well as ISO/IEC 14888
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/sm2"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/sm2"
readme = "README.md"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "shangmi"]
edition = "2021"
rust-version = "1.65"

[dependencies]
elliptic-curve = { version = "0.13", default-features = false, features = ["hazmat", "sec1"] }

# optional dependencies
primeorder = { version = "0.13.1", optional = true, path = "../primeorder" }

[features]
default = ["pem", "std"]
alloc = ["elliptic-curve/alloc"]
std = ["alloc", "elliptic-curve/std"]

pem = ["elliptic-curve/pem", "pkcs8"]
pkcs8 = ["elliptic-curve/pkcs8"]
wip-arithmetic-do-not-use = ["elliptic-curve/arithmetic", "primeorder"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
