[package]
name = "bign256"
version = "0.1.0"
description = """
Pure Rust implementation of the Bign P-256 (a.k.a. bign-curve256v1)
elliptic curve as defined in STB 34.101.45-2013, with
general purpose curve arithmetic
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/bign-curve256v1"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/bign-curve256v1"
readme = "README.md"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "nist", "bign-curve256v1", "bignp256"]
edition = "2021"
rust-version = "1.65"

[dependencies]
elliptic-curve = { version = "0.13.1", features = ["hazmat", "sec1", "arithmetic"] }
primeorder = { version = "0.13", path = "../primeorder" }

ecdsa-core = { version = "0.16", package = "ecdsa", optional = true, default-features = false, features = ["der"] }
serdect = { version = "0.2", optional = true, default-features = false }
belt-hash = { version = "0.1.0", optional = true }

[dev-dependencies]
hex-literal = "0.3.4"

[features]
default = ["ecdsa", "pkcs8", "std"]
alloc = ["ecdsa-core?/alloc", "elliptic-curve/alloc"]
std = ["alloc", "ecdsa-core?/std", "elliptic-curve/std"]

bits = ["elliptic-curve/bits"]
digest = ["ecdsa-core/digest", "ecdsa-core/hazmat"]
ecdsa = ["ecdsa-core/signing", "ecdsa-core/verifying", "dep:belt-hash"]
pkcs8 = ["ecdsa-core/pkcs8", "elliptic-curve/pkcs8"]
serde = ["ecdsa-core/serde", "elliptic-curve/serde", "serdect"]
belt-hash = ["digest"]
