[package]
name = "p224"
version = "0.13.0"
description = """
Pure Rust implementation of the NIST P-224 (a.k.a. secp224r1) elliptic curve
as defined in SP 800-186
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/p224"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/p224"
readme = "README.md"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "nist", "secp224r1"]
edition = "2021"
rust-version = "1.65"

[dependencies]
elliptic-curve = { version = "0.13", default-features = false, features = ["hazmat", "sec1"] }

# optional features
const-oid = { version = "0.9", optional = true }
primeorder = { version = "0.13", optional = true, path = "../primeorder" }

[features]
default = ["pem", "std"]
alloc = ["elliptic-curve/alloc"]
std = ["alloc", "elliptic-curve/std"]

algorithm-identifier = ["elliptic-curve/pkcs8", "const-oid"]
pem = ["elliptic-curve/pem", "pkcs8"]
pkcs8 = ["elliptic-curve/pkcs8"]
wip-arithmetic-do-not-use = ["dep:primeorder"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
