[package]
name = "p521"
version = "0.11.1"
description = "Pure Rust implementation of the NIST P-521 (a.k.a. secp521r1) elliptic curve"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/p521"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/p521"
readme = "README.md"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "nist", "secp521r1"]
edition = "2021"
rust-version = "1.57"

[dependencies]
elliptic-curve = { version = "0.12.3", default-features = false, features = ["hazmat", "sec1"] }

[features]
default = ["pem", "std"]
alloc = ["elliptic-curve/alloc"]
std = ["alloc", "elliptic-curve/std"] # TODO: use weak activation for `ecdsa-core/std` when available

jwk = ["elliptic-curve/jwk"]
pem = ["elliptic-curve/pem", "pkcs8"]
pkcs8 = ["elliptic-curve/pkcs8"]
