[package]
name = "p521"
description = "NIST P-521 (secp521r1) elliptic curve"
version = "0.0.0"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/elliptic-curve"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/p521"
readme = "README.md"
edition = "2018"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "nist", "secp521r1"]

[dependencies]
elliptic-curve = { version = "0.12.1", default-features = false, features = ["hazmat", "sec1"] }

[features]
std = ["elliptic-curve/std"]

[package.metadata.docs.rs]
all-features = true
