[package]
name = "p521"
description = "NIST P-521 elliptic curve"
version = "0.0.0"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
documentation = "https://docs.rs/elliptic-curve"
repository = "https://github.com/RustCrypto/elliptic-curves/tree/master/p521"
readme = "README.md"
edition = "2018"
categories = ["cryptography", "no-std"]
keywords = ["crypto", "ecc", "nist"]

[dependencies.elliptic-curve]
version = "0.3"
path = "../elliptic-curve-crate"
default-features = false
features = ["weierstrass"]

[features]
std = ["elliptic-curve/std"]

[package.metadata.docs.rs]
all-features = true
