name: p384

on:
  pull_request:
    paths:
      - "p384/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: p384

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  # TODO(tarcieri): test arithmetic on 32-bit platforms
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.57.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          profile: minimal
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features
      # TODO(tarcieri): currently 64-bit only
      # - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features broken-arithmetic-do-not-use
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features ecdsa
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features jwk
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features pem
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features pkcs8
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features serde
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features sha384
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features voprf
      - run: cargo build --target ${{ matrix.target }} --release --no-default-features --features ecdsa,jwk,pem,pkcs8,serde,sha384,voprf

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.57.0 # MSRV
          - stable
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true
        profile: minimal
    - run: cargo check --all-features
    - run: cargo test --no-default-features
    - run: cargo test
    - run: cargo test --all-features
